CREATE TABLE IF NOT EXISTS projects (id UUID PRIMARY KEY, slug TEXT UNIQUE NOT NULL, name TEXT NOT NULL, constitution_version TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS tasks (id UUID PRIMARY KEY, project_id UUID REFERENCES projects(id), command TEXT, objective TEXT NOT NULL, lane TEXT NOT NULL, primary_skill_id TEXT NOT NULL, skill_version TEXT NOT NULL, risk_level TEXT NOT NULL, status TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS task_events (id UUID PRIMARY KEY, task_id UUID NOT NULL REFERENCES tasks(id), event_type TEXT NOT NULL, payload JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS task_artifacts (id UUID PRIMARY KEY, task_id UUID NOT NULL REFERENCES tasks(id), artifact_type TEXT NOT NULL, uri TEXT NOT NULL, content_hash TEXT, schema_version TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS evidence_records (id UUID PRIMARY KEY, task_id UUID REFERENCES tasks(id), source TEXT NOT NULL, observed_at TIMESTAMPTZ, payload JSONB NOT NULL, content_hash TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS approvals (id UUID PRIMARY KEY, task_id UUID NOT NULL REFERENCES tasks(id), action_type TEXT NOT NULL, target TEXT NOT NULL, payload_hash TEXT NOT NULL, status TEXT NOT NULL, issued_at TIMESTAMPTZ, expires_at TIMESTAMPTZ);
CREATE TABLE IF NOT EXISTS trace_events (id UUID PRIMARY KEY, task_id UUID REFERENCES tasks(id), event_type TEXT NOT NULL, redacted_payload JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS evaluation_results (id UUID PRIMARY KEY, task_id UUID REFERENCES tasks(id), fixture_id TEXT NOT NULL, result JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS routing_decisions (id UUID PRIMARY KEY, task_id UUID REFERENCES tasks(id), model_alias TEXT NOT NULL, provider_ref TEXT, decision JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
