#!/usr/bin/env python3
"""
sync-roster.py — regenerates the entry-count/roster listings in README.md,
AoA-RESEARCH-PROMPT.md, and AoA-QUICK-PROMPT.md directly from the actual
files in personas/, agents/, workflows/, techniques/, modes/.

WHY THIS EXISTS:
On 2026-07-15 the research prompts were caught listing 10 personas / 5
agents / 0 workflows while the repo actually had 23 / 12 / 8 (plus two
layers — techniques, modes — the prompts didn't mention at all). Root
cause: three files were hand-edited independently every session, and at
least one batch of entries (sieve, concierge, objection-loop) was created
locally but never committed, so even the "current" counts silently fell
behind. Prose-editing counts from memory doesn't scale past a few sessions.

RUN THIS before any commit that adds/removes/renames an entry, and as a
final step before ending an extraction session.

README.md keeps hand-curated one-line blurbs (better prose than any
auto-pulled field), so this script only CHECKS README's counts and entry
set against the filesystem and warns on drift — it does not rewrite
README's prose. AoA-RESEARCH-PROMPT.md and AoA-QUICK-PROMPT.md use plain
ID lists with no curated prose, so those two ARE fully autogenerated
between the AUTOGEN:ROSTER markers.

Usage: python3 sync-roster.py [--check]
  --check   exit 1 if anything is stale (for CI / pre-commit use), no writes to prompt files
"""
import os
import re
import sys

LAYERS = ["personas", "agents", "workflows", "techniques", "modes", "teams"]
START_MARK = "<!-- AUTOGEN:ROSTER:START -->"
END_MARK = "<!-- AUTOGEN:ROSTER:END -->"


def get_ids(layer_dir):
    if not os.path.isdir(layer_dir):
        return []
    return sorted(f[:-3] for f in os.listdir(layer_dir) if f.endswith(".md"))


def get_field(path, field):
    with open(path) as f:
        content = f.read()
    m = re.search(rf"^{field}:\s*(.+)$", content, re.M)
    return m.group(1).strip() if m else ""


def build_prompt_block(counts, entries):
    lines = [START_MARK, ""]
    lines.append("**This list is autogenerated from the repo file listing by "
                  "scripts/sync-roster.py. If it and the live repo disagree, "
                  "the repo is correct — re-run the script.**")
    lines.append("")
    for layer in LAYERS:
        lines.append(f"### {layer.capitalize()} ({counts[layer]})")
        lines.append(", ".join(entries[layer]))
        lines.append("")
    lines.append(END_MARK)
    return "\n".join(lines)


def replace_block(text, new_block):
    pattern = re.compile(re.escape(START_MARK) + r".*?" + re.escape(END_MARK), re.S)
    if pattern.search(text):
        return pattern.sub(new_block, text)
    # No existing markers: caller decides where to insert manually first time.
    return None


def main():
    check_only = "--check" in sys.argv
    entries = {layer: get_ids(layer) for layer in LAYERS}
    counts = {layer: len(entries[layer]) for layer in LAYERS}
    total = sum(counts.values())

    changed = False

    # README.md holds hand-curated one-line blurbs that read better than any
    # auto-pulled YAML field — don't auto-rewrite its prose. Instead, just
    # check that its entry COUNT and ID SET match the filesystem, and warn
    # if not. The prompt files use plain ID lists, which ARE safe to
    # regenerate exactly, so those stay fully autogenerated.
    if os.path.exists("README.md"):
        with open("README.md") as f:
            readme_text = f.read()
        mismatches = []
        for layer in LAYERS:
            heading_match = re.search(
                rf"### {layer.capitalize()}s? \((\d+)\)" if layer != "workflows"
                else r"### Workflows \((\d+)\)",
                readme_text, re.I)
            claimed = int(heading_match.group(1)) if heading_match else None
            actual = counts[layer]
            if claimed != actual:
                mismatches.append(f"  {layer}: README says {claimed}, filesystem has {actual}")
            # also check every actual ID is mentioned somewhere in the file
            # (README writes IDs as Title Case with spaces, e.g. "raw-cut" ->
            # "Raw Cut", so normalize both sides before comparing)
            readme_norm = readme_text.lower().replace("-", " ")
            missing = [
                eid for eid in entries[layer]
                if eid.lower().replace("-", " ") not in readme_norm
            ]
            if missing:
                mismatches.append(f"  {layer}: not mentioned in README: {missing}")
        if mismatches:
            print("README.md DRIFT DETECTED (not auto-fixed — edit by hand, blurbs are curated):")
            print("\n".join(mismatches))
            changed = True
        else:
            print("README.md: counts and entry set match filesystem, OK")

    targets = {
        "AoA-RESEARCH-PROMPT.md": build_prompt_block(counts, entries),
        "AoA-QUICK-PROMPT.md": build_prompt_block(counts, entries),
    }

    for fname, new_block in targets.items():
        if not os.path.exists(fname):
            print(f"SKIP {fname}: not found")
            continue
        with open(fname) as f:
            old_text = f.read()
        new_text = replace_block(old_text, new_block)
        if new_text is None:
            print(f"WARN {fname}: no {START_MARK} ... {END_MARK} markers found. "
                  f"Add markers around the roster section once, manually, then re-run.")
            continue
        if new_text != old_text:
            changed = True
            if not check_only:
                with open(fname, "w") as f:
                    f.write(new_text)
                print(f"UPDATED {fname}")
            else:
                print(f"WOULD UPDATE {fname}")

    print(f"\nTotals: {counts} = {total} entries")

    if check_only and changed:
        sys.exit(1)


if __name__ == "__main__":
    main()
